name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          docker build . --file Dockerfile --tag forestsystem/atm9-server:${DATE_TAG} --tag forestsystem/atm9-server:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          docker push forestsystem/atm9-server:${DATE_TAG}
          docker push forestsystem/atm9-server:latest
